apps/freeboard/urls.py
from django.urls import path, include
from apps.freeboard.views import views

urlpatterns = [
    path('', views.show_trasaction_list, name='transactions')
]

apps/userinfo/urls.py
from django.urls import path
from apps.userinfo.views import views

app_name = 'userinfo'

urlpatterns = [
    path('', views.login, name='login'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('freeboard/', include('apps.freeboard.urls')),
    path('', include('apps.userinfo.urls')),
]

apps/freeboard/models/models.py
from django.db import models


# Create your models here.
class Transaction(models.Model):
    TransactionID = models.IntegerField()
    ProductID = models.IntegerField()
    ReferenceOrderID = models.IntegerField()
    ReferenceOrderLineID = models.IntegerField()
    TransactionDate = models.DateTimeField()
    TransactionType = models.CharField(max_length=2)
    Quantity = models.IntegerField()
    ActualCost = models.IntegerField()
    ModifiedDate = models.DateTimeField

apps/userinfo/models.py
from django.db import models

# Create your models here.
class UserInfo(models.Model):
    userid = models.CharField(max_length=30)
    password = models.CharField(max_length=50)
    confirm_password = models.CharField(max_length=50)
    email = models.CharField(max_length=50)
    username = models.CharField(max_length=30)

apps/userinfo/forms.py
from django import forms
from .models import UserInfo

class LoginForm(forms.Form):
    userid = forms.CharField(error_messages={
        "required": "아이디를 입력해주세요."
    }, max_length=30, label="아이디")
    password = forms.CharField(error_messages={
        "required": "비밀번호를 입력해주세요."
    }, widget= forms.PasswordInput, max_length=50, label="비밀번호")

apps/freeboard/views/views.py
from django.shortcuts import render
from common.sql_helper import SqlHelper
from common.convert_model import ModelMapper
from apps.freeboard.models.models import Transaction

# Create your views here.
def show_trasaction_list(request):
    sql_helper = SqlHelper()
    model_mapper = ModelMapper()

    data = sql_helper.get_data_list('[dbo].[USP_TransactionHistory_Select_List]')
    list = [model_mapper.make_instance(Transaction(), item) for item in data]

    return render(request, "freeboard/index.html", {
        'transactions': list
    })



# def get_data_list(procedure_name, parameters=None):
#     cursor = connection.cursor()
#     try:
#         cursor.execute(procedure_name, parameters)
#         row_data = cursor.fetchall()
#
#         data_title = [item[0] for item in cursor.description]
#         data = [dict(zip(data_title, item)) for item in row_data]
#     except Exception as e:
#         print(e)
#     finally:
#         cursor.close()
#
#     return data
#
# '''
#     Data To Object
# '''
# def make_instance(instance, values):
#     attributes = instance.__dict__.keys()
#
#     for attribute in attributes:
#         try:
#             # field names from oracle sp are UPPER CASE
#             # we want to put PIC_ID in pic_id etc.
#             # setattr(instance, a, values.get(a))
#             # del values.get(a)
#             if attribute in values.keys():
#                 setattr(instance, attribute, values.get(attribute))
#                 values.pop(attribute)
#         except AttributeError:
#             pass
#         except Exception as e:
#             print(e)
#
#     for other_key in values.keys():
#         setattr(instance, other_key, values.get(other_key))
#
#     return instance

apps/userinfo/views/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from ..forms import LoginForm
from ..models import UserInfo
from common.sql_helper import SqlHelper
from common.convert_model import ModelMapper

# Create your views here.
def login(request):
    sql_helper = SqlHelper()
    model_mapper = ModelMapper()
    userdata = None

    if request.method == "POST":
        login_form = LoginForm(request.POST)

        if login_form.is_valid():
            userid = login_form.cleaned_data['userid']
            password = login_form.cleaned_data['password']

            if request.COOKIES.get('userinfo'):
                return redirect('freeboard/')

            parameters = (userid, password)
            userdata = sql_helper.get_data_list('[dbo].[USP_FREEBOARD_USERINFO_TB_SEL] @USERID=%s, @PASSWORD=%s', parameters)
            userinfo = [model_mapper.make_instance(UserInfo(), item) for item in userdata]

            if userinfo is not None:
                response = redirect('freeboard/')
                response.set_cookie('userinfo', userinfo)
                return response
    else:
        login_form = LoginForm()

    return render(request, 'userinfo/login_form.html', {
        'login_form': login_form
    })

templates/freeboard/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  <table>
    <tr>
        <th>TransactionID</th>
        <th>ProductID</th>
        <th>ReferenceOrderID</th>
        <th>ReferenceOrderLineID</th>
        <th>TransactionDate</th>
        <th>TransactionType</th>
        <th>Quantity</th>
        <th>ActualCost</th>
        <th>ModifiedDate</th>
    </tr>
    {% if transactions %}
        {% for trans in transactions %}
            <tr>
                <td>{{ trans.TransactionID }}</td>
                <td>{{ trans.ProductID }}</td>
                <td>{{ trans.ReferenceOrderID }}</td>
                <td>{{ trans.ReferenceOrderLineID }}</td>
                <td>{{ trans.TransactionDate }}</td>
                <td>{{ trans.TransactionType }}</td>
                <td>{{ trans.Quantity }}</td>
                <td>{{ trans.ActualCost }}</td>
                <td>{{ trans.ModifiedDate }}</td>
            </tr>
        {% endfor %}
     {% else %}
      <tr><td colspan="9">NOB</td> </tr>
     {% endif %}
  </table>
</body>
</html>

templates/userinfo/login_form.html
<form action="{% url 'userinfo:login' %}" method="post">
    {% csrf_token %}
    {{ login_form }}
    <input type="submit" value="로그인" />
</form>